export const COUNTRIES = [
  "Afghanistan","Armenia","Azerbaijan","Bahrain","Bangladesh","Bhutan","Brunei",
  "Cambodia","China","Cyprus","Georgia","India","Indonesia","Iran","Iraq",
  "Israel","Japan","Jordan","Kazakhstan","Kuwait","Kyrgyzstan","Laos","Lebanon",
  "Malaysia","Maldives","Mongolia","Myanmar","Nepal","North Korea","Oman",
  "Pakistan","Palestine","Philippines","Qatar","Saudi Arabia","Singapore",
  "South Korea","Sri Lanka","Syria","Taiwan","Tajikistan","Thailand","Timor-Leste",
  "Turkey","Turkmenistan","UAE","Uzbekistan","Vietnam","Yemen",
  "Albania","Andorra","Austria","Belarus","Belgium","Bosnia and Herzegovina",
  "Bulgaria","Croatia","Czech Republic","Denmark","Estonia","Finland","France",
  "Germany","Greece","Hungary","Iceland","Ireland","Italy","Kosovo","Latvia",
  "Liechtenstein","Lithuania","Luxembourg","Malta","Moldova","Monaco","Montenegro",
  "Netherlands","North Macedonia","Norway","Poland","Portugal","Romania","Russia",
  "San Marino","Serbia","Slovakia","Slovenia","Spain","Sweden","Switzerland",
  "Ukraine","United Kingdom","Vatican City",
  "Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","Cameroon",
  "Cape Verde","Central African Republic","Chad","Comoros","Congo","DR Congo",
  "Djibouti","Egypt","Equatorial Guinea","Eritrea","Eswatini","Ethiopia","Gabon",
  "Gambia","Ghana","Guinea","Guinea-Bissau","Ivory Coast","Kenya","Lesotho",
  "Liberia","Libya","Madagascar","Malawi","Mali","Mauritania","Mauritius",
  "Morocco","Mozambique","Namibia","Niger","Nigeria","Rwanda","Sao Tome",
  "Senegal","Seychelles","Sierra Leone","Somalia","South Africa","South Sudan",
  "Sudan","Tanzania","Togo","Tunisia","Uganda","Zambia","Zimbabwe",
  "Antigua and Barbuda","Bahamas","Barbados","Belize","Canada","Costa Rica",
  "Cuba","Dominica","Dominican Republic","El Salvador","Grenada","Guatemala",
  "Haiti","Honduras","Jamaica","Mexico","Nicaragua","Panama","Saint Kitts",
  "Saint Lucia","Saint Vincent","Trinidad and Tobago","USA",
  "Argentina","Bolivia","Brazil","Chile","Colombia","Ecuador","Guyana",
  "Paraguay","Peru","Suriname","Uruguay","Venezuela",
  "Australia","Fiji","Kiribati","Marshall Islands","Micronesia","Nauru",
  "New Zealand","Palau","Papua New Guinea","Samoa","Solomon Islands","Tonga",
  "Tuvalu","Vanuatu",
];

export const VISA_TYPES = [
  "Work Visa","Study Visa","Tourist Visa","Business Visa",
  "Family Visa","Sponsorship","PR / Immigration","Transit Visa",
  "Medical Visa","Religious Visa","Diplomatic Visa",
];

export interface Ad {
  id: string;
  title: string;
  description: string;
  country: string;
  category: string;
  visaType?: string;
  price: number;
  currency: string;
  processingTime?: string;
  verified: boolean;
  sellerName?: string;
  sellerId?: string;
  rating?: string;
  reviewCount?: number;
  requirements?: string[];
  createdAt?: string;
}

export const MOCK_ADS: Ad[] = [
  {
    id: "1",
    title: "Canada Express Entry — PR Assistance",
    description: "Full Express Entry profile evaluation, CRS score optimization, document review, and submission assistance. 200+ successful cases.",
    country: "Canada",
    category: "Work Visa",
    visaType: "PR / Immigration",
    price: 499,
    currency: "USDT",
    processingTime: "6-8 months",
    verified: true,
    sellerName: "ImmigrationPro",
    sellerId: "provider1",
    rating: "4.9",
    reviewCount: 234,
    requirements: [
      "Valid Passport (min 6 months validity)",
      "IELTS or CELPIP language test result",
      "Educational credentials assessment (ECA)",
      "Work experience proof (NOC code letters)",
      "Passport-size photographs",
    ],
    createdAt: "June 1, 2026",
  },
  {
    id: "2",
    title: "UK Student Visa — Full Service",
    description: "Complete UK student visa application support including CAS guidance, financial statements review, and biometric appointment scheduling.",
    country: "United Kingdom",
    category: "Study Visa",
    visaType: "Study Visa",
    price: 299,
    currency: "USDT",
    processingTime: "3-4 weeks",
    verified: true,
    sellerName: "Global Edu",
    sellerId: "provider2",
    rating: "4.7",
    reviewCount: 89,
    requirements: [
      "University offer letter (CAS number)",
      "Bank statements (last 6 months)",
      "English language certificate (IELTS 6.0+)",
      "Valid passport",
      "Tuberculosis test (if applicable)",
    ],
    createdAt: "May 20, 2026",
  },
  {
    id: "3",
    title: "Germany Skilled Worker Visa — IT Professionals",
    description: "End-to-end Germany Skilled Worker Visa. Qualification recognition, blocked account setup, and embassy appointment guidance.",
    country: "Germany",
    category: "Work Visa",
    visaType: "Work Visa",
    price: 399,
    currency: "USDT",
    processingTime: "8-10 weeks",
    verified: true,
    sellerName: "EuroPath Immigration",
    sellerId: "provider3",
    rating: "4.8",
    reviewCount: 156,
    requirements: [
      "Recognized degree or qualification",
      "B1 German or English proficiency",
      "Employment contract or job offer",
      "Health insurance proof",
      "Blocked account (€11,208)",
    ],
    createdAt: "June 5, 2026",
  },
  {
    id: "4",
    title: "UAE Work Visa — IT & Tech Sector",
    description: "Fast-track UAE employment visa for IT professionals. Emirates ID processing and health insurance linkage included.",
    country: "UAE",
    category: "Work Visa",
    visaType: "Work Visa",
    price: 199,
    currency: "USDT",
    processingTime: "2-3 weeks",
    verified: true,
    sellerName: "Dubai Visa Center",
    sellerId: "provider4",
    rating: "4.6",
    reviewCount: 312,
    requirements: [
      "IT-related degree or 3 years experience",
      "Job offer from UAE employer",
      "Medical fitness certificate",
      "Passport copy + photographs",
      "Educational certificates",
    ],
    createdAt: "June 8, 2026",
  },
  {
    id: "5",
    title: "Australia Skilled Migration — Subclass 189",
    description: "Subclass 189/190 skilled migration visa. Skills assessment, EOI lodgement, and state nomination assistance.",
    country: "Australia",
    category: "PR / Immigration",
    visaType: "PR / Immigration",
    price: 599,
    currency: "USDT",
    processingTime: "10-14 months",
    verified: true,
    sellerName: "AusImmigration Pro",
    sellerId: "provider5",
    rating: "4.9",
    reviewCount: 201,
    requirements: [
      "Skills assessment from relevant body",
      "IELTS 6.0+ or equivalent",
      "Points test score 65+",
      "Age under 45",
      "Health and character certificates",
    ],
    createdAt: "May 15, 2026",
  },
  {
    id: "6",
    title: "Saudi Arabia Work Visa — Construction",
    description: "Complete Saudi work visa for construction and engineering professionals. Attestation, medical, and Iqama guidance included.",
    country: "Saudi Arabia",
    category: "Work Visa",
    visaType: "Work Visa",
    price: 149,
    currency: "USDT",
    processingTime: "3-5 weeks",
    verified: true,
    sellerName: "Gulf Visa Pro",
    sellerId: "provider6",
    rating: "4.5",
    reviewCount: 445,
    requirements: [
      "Valid passport (2+ years)",
      "Job offer from Saudi employer",
      "Medical fitness certificate",
      "Educational certificates (attested)",
      "Police clearance certificate",
    ],
    createdAt: "June 10, 2026",
  },
  {
    id: "7",
    title: "Romania Work Visa — Skilled Workers",
    description: "Romania work permit for skilled workers. Job placement assistance, visa processing, and accommodation support.",
    country: "Romania",
    category: "Work Visa",
    visaType: "Work Visa",
    price: 350,
    currency: "USDT",
    processingTime: "6-8 weeks",
    verified: true,
    sellerName: "EuroWork Agency",
    sellerId: "provider7",
    rating: "4.4",
    reviewCount: 78,
    requirements: [
      "Valid passport",
      "Work contract from Romanian employer",
      "Educational certificates",
      "Medical certificate",
      "Accommodation proof",
    ],
    createdAt: "June 12, 2026",
  },
  {
    id: "8",
    title: "Schengen Tourist Visa — Multiple Entry",
    description: "Multiple entry Schengen visa for 26 European countries. Hotel bookings, travel insurance, and interview coaching included.",
    country: "Germany",
    category: "Tourist Visa",
    visaType: "Tourist Visa",
    price: 120,
    currency: "USDT",
    processingTime: "2-3 weeks",
    verified: true,
    sellerName: "EuroVisa Express",
    sellerId: "provider8",
    rating: "4.7",
    reviewCount: 523,
    requirements: [
      "Valid passport (3+ months beyond stay)",
      "Bank statements (last 3 months)",
      "Travel insurance (min €30,000)",
      "Hotel bookings",
      "Return flight tickets",
    ],
    createdAt: "June 13, 2026",
  },
];

// ── ADMIN DATA ──

export const ADMIN_USERS = [
  {
    id: "u1",
    name: "Ahmad Khan",
    email: "ahmad@email.com",
    role: "seeker",
    verification: 3,
    trustScore: 82,
    status: "active",
    joined: "Jan 2026",
    country: "Pakistan",
    totalTransactions: 3,
  },
  {
    id: "u2",
    name: "ImmigrationPro",
    email: "info@immigrationpro.ca",
    role: "provider",
    verification: 4,
    trustScore: 96,
    status: "active",
    joined: "Mar 2025",
    country: "Canada",
    totalTransactions: 312,
  },
  {
    id: "u3",
    name: "Sara Khan",
    email: "sara@email.com",
    role: "seeker",
    verification: 2,
    trustScore: 65,
    status: "active",
    joined: "Feb 2026",
    country: "Pakistan",
    totalTransactions: 1,
  },
  {
    id: "u4",
    name: "GlobeTrek Agency",
    email: "info@globetrek.com",
    role: "provider",
    verification: 3,
    trustScore: 45,
    status: "suspended",
    joined: "Dec 2025",
    country: "UAE",
    totalTransactions: 89,
  },
  {
    id: "u5",
    name: "Muhammad Ali",
    email: "mali@email.com",
    role: "seeker",
    verification: 1,
    trustScore: 30,
    status: "active",
    joined: "Jun 2026",
    country: "Pakistan",
    totalTransactions: 0,
  },
];

export const KYC_MOCK_USERS = [
  {
    id: "kyc1",
    principal: "user-sara-001",
    name: "Sara Khan",
    country: "Pakistan",
    docType: "Passport",
    submittedDate: "June 14, 2026",
    status: "pending",
    level: 3,
  },
  {
    id: "kyc2",
    principal: "user-mali-002",
    name: "Muhammad Ali",
    country: "Pakistan",
    docType: "National ID",
    submittedDate: "June 13, 2026",
    status: "pending",
    level: 3,
  },
  {
    id: "kyc3",
    principal: "user-ahmed-003",
    name: "Ahmed Raza",
    country: "Pakistan",
    docType: "Passport",
    submittedDate: "June 12, 2026",
    status: "approved",
    level: 3,
  },
  {
    id: "kyc4",
    principal: "user-euro-004",
    name: "EuroWork Agency",
    country: "Romania",
    docType: "Company Registration",
    submittedDate: "June 11, 2026",
    status: "pending",
    level: 4,
  },
];

export const ADMIN_ADS = [
  {
    id: "ad1",
    title: "Canada Express Entry — PR Assistance",
    seller: "ImmigrationPro",
    country: "Canada",
    status: "active",
    created: "June 1, 2026",
  },
  {
    id: "ad2",
    title: "UK Student Visa — Full Service",
    seller: "Global Edu",
    country: "United Kingdom",
    status: "active",
    created: "May 20, 2026",
  },
  {
    id: "ad3",
    title: "Germany Skilled Worker Visa",
    seller: "EuroPath Immigration",
    country: "Germany",
    status: "active",
    created: "June 5, 2026",
  },
  {
    id: "ad4",
    title: "UAE Work Visa — IT Sector",
    seller: "Dubai Visa Center",
    country: "UAE",
    status: "suspended",
    created: "June 8, 2026",
  },
  {
    id: "ad5",
    title: "Romania Work Visa",
    seller: "EuroWork Agency",
    country: "Romania",
    status: "active",
    created: "June 12, 2026",
  },
];

export const ADMIN_DISPUTES = [
  {
    id: "DSP-001",
    transactionId: "TXN-003",
    buyer: "Ahmad Khan",
    seller: "Dubai Visa Center",
    amount: 199,
    reason: "Provider stopped responding after document submission",
    status: "underReview",
    filed: "May 15, 2026",
    priority: "high",
  },
  {
    id: "DSP-002",
    transactionId: "TXN-007",
    buyer: "Sara Khan",
    seller: "GlobeTrek Agency",
    amount: 350,
    reason: "Visa rejected — provider promised refund but not delivered",
    status: "open",
    filed: "June 10, 2026",
    priority: "high",
  },
  {
    id: "DSP-003",
    transactionId: "TXN-012",
    buyer: "Muhammad Ali",
    seller: "Gulf Visa Pro",
    amount: 149,
    reason: "Documents submitted but no update for 3 weeks",
    status: "resolvedBuyer",
    filed: "May 1, 2026",
    priority: "medium",
  },
];
