/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'suspended' : null } |
  { 'draft' : null };
export interface Dispute {
  'status' : DisputeStatus,
  'resolutionNotes' : string,
  'evidence' : string,
  'transactionId' : string,
  'reason' : string,
}
export type DisputeStatus = { 'closed' : null } |
  { 'underReview' : null } |
  { 'open' : null } |
  { 'resolvedBuyer' : null } |
  { 'resolvedSeller' : null };
export type ExternalBlob = Uint8Array;
export type KYCStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface KYCSubmission {
  'status' : KYCStatus,
  'documentBlob' : [] | [ExternalBlob],
  'documentType' : string,
  'reviewerNotes' : string,
  'user' : Principal,
  'description' : string,
}
export interface Listing {
  'id' : string,
  'status' : AdStatus,
  'title' : string,
  'views' : bigint,
  'seller' : Principal,
  'processingTime' : string,
  'currency' : string,
  'category' : string,
  'originCountry' : string,
  'price' : bigint,
  'destinationCountry' : string,
  'requirements' : Array<string>,
  'images' : Array<ExternalBlob>,
}
export interface Message {
  'text' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Notification {
  'title' : string,
  'notifType' : NotificationType,
  'read' : boolean,
  'user' : Principal,
  'message' : string,
}
export type NotificationType = { 'kycUpdate' : null } |
  { 'transaction' : null } |
  { 'message' : null } |
  { 'dispute' : null } |
  { 'systemNotification' : null };
export type Time = bigint;
export type TransactionStatus = { 'disputed' : null } |
  { 'initiated' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'escrowed' : null };
export interface User {
  'bio' : string,
  'principal' : Principal,
  'country' : string,
  'balance' : bigint,
  'role' : UserRole,
  'trustScore' : bigint,
  'languages' : Array<string>,
  'verification' : VerificationLevel,
}
export interface UserProfile {
  'bio' : string,
  'country' : string,
  'balance' : bigint,
  'role' : UserRole,
  'trustScore' : bigint,
  'languages' : Array<string>,
  'verification' : VerificationLevel,
}
export type UserRole = { 'admin' : null } |
  { 'moderator' : null } |
  { 'seller' : null } |
  { 'buyer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationLevel = { 'documentVerified' : null } |
  { 'basic' : null } |
  { 'fullyVerified' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createConversation' : ActorMethod<[string, Principal, string], undefined>,
  'createDispute' : ActorMethod<[string, string, string], undefined>,
  'createListing' : ActorMethod<[string, string, bigint], string>,
  'createReview' : ActorMethod<[string, string, bigint, string], undefined>,
  'createUser' : ActorMethod<[string, string, UserRole], undefined>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllListingsBySeller' : ActorMethod<[Principal], Array<Listing>>,
  'getAllOpenDisputes' : ActorMethod<[], Array<Dispute>>,
  'getAllSuspendedListings' : ActorMethod<[], Array<Listing>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getListing' : ActorMethod<[string], Listing>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getPendingKYCSubmissions' : ActorMethod<[], Array<KYCSubmission>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementListingViews' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'recordTransaction' : ActorMethod<[Principal, string, bigint], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitKYC' : ActorMethod<[string, string], undefined>,
  'suspendListing' : ActorMethod<[string], undefined>,
  'updateDisputeStatus' : ActorMethod<
    [string, DisputeStatus, string],
    undefined
  >,
  'updateKYCStatus' : ActorMethod<[Principal, KYCStatus, string], undefined>,
  'updateListing' : ActorMethod<
    [string, string, string, bigint, AdStatus],
    undefined
  >,
  'updateTransactionStatus' : ActorMethod<
    [string, TransactionStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];