/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'moderator' : IDL.Null,
  'seller' : IDL.Null,
  'buyer' : IDL.Null,
});
export const AdStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'suspended' : IDL.Null,
  'draft' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'status' : AdStatus,
  'title' : IDL.Text,
  'views' : IDL.Nat,
  'seller' : IDL.Principal,
  'processingTime' : IDL.Text,
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'originCountry' : IDL.Text,
  'price' : IDL.Nat,
  'destinationCountry' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'images' : IDL.Vec(ExternalBlob),
});
export const DisputeStatus = IDL.Variant({
  'closed' : IDL.Null,
  'underReview' : IDL.Null,
  'open' : IDL.Null,
  'resolvedBuyer' : IDL.Null,
  'resolvedSeller' : IDL.Null,
});
export const Dispute = IDL.Record({
  'status' : DisputeStatus,
  'resolutionNotes' : IDL.Text,
  'evidence' : IDL.Text,
  'transactionId' : IDL.Text,
  'reason' : IDL.Text,
});
export const VerificationLevel = IDL.Variant({
  'documentVerified' : IDL.Null,
  'basic' : IDL.Null,
  'fullyVerified' : IDL.Null,
});
export const User = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'country' : IDL.Text,
  'balance' : IDL.Nat,
  'role' : UserRole,
  'trustScore' : IDL.Nat,
  'languages' : IDL.Vec(IDL.Text),
  'verification' : VerificationLevel,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'country' : IDL.Text,
  'balance' : IDL.Nat,
  'role' : UserRole,
  'trustScore' : IDL.Nat,
  'languages' : IDL.Vec(IDL.Text),
  'verification' : VerificationLevel,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const KYCStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const KYCSubmission = IDL.Record({
  'status' : KYCStatus,
  'documentBlob' : IDL.Opt(ExternalBlob),
  'documentType' : IDL.Text,
  'reviewerNotes' : IDL.Text,
  'user' : IDL.Principal,
  'description' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'kycUpdate' : IDL.Null,
  'transaction' : IDL.Null,
  'message' : IDL.Null,
  'dispute' : IDL.Null,
  'systemNotification' : IDL.Null,
});
export const Notification = IDL.Record({
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'read' : IDL.Bool,
  'user' : IDL.Principal,
  'message' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'disputed' : IDL.Null,
  'initiated' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'escrowed' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createConversation' : IDL.Func([IDL.Text, IDL.Principal, IDL.Text], [], []),
  'createDispute' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createListing' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'createReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAllOpenDisputes' : IDL.Func([], [IDL.Vec(Dispute)], ['query']),
  'getAllSuspendedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getPendingKYCSubmissions' : IDL.Func(
      [],
      [IDL.Vec(KYCSubmission)],
      ['query'],
    ),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementListingViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'recordTransaction' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitKYC' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'suspendListing' : IDL.Func([IDL.Text], [], []),
  'updateDisputeStatus' : IDL.Func([IDL.Text, DisputeStatus, IDL.Text], [], []),
  'updateKYCStatus' : IDL.Func([IDL.Principal, KYCStatus, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, AdStatus],
      [],
      [],
    ),
  'updateTransactionStatus' : IDL.Func([IDL.Text, TransactionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'seller' : IDL.Null,
    'buyer' : IDL.Null,
  });
  const AdStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'suspended' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'status' : AdStatus,
    'title' : IDL.Text,
    'views' : IDL.Nat,
    'seller' : IDL.Principal,
    'processingTime' : IDL.Text,
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'originCountry' : IDL.Text,
    'price' : IDL.Nat,
    'destinationCountry' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'images' : IDL.Vec(ExternalBlob),
  });
  const DisputeStatus = IDL.Variant({
    'closed' : IDL.Null,
    'underReview' : IDL.Null,
    'open' : IDL.Null,
    'resolvedBuyer' : IDL.Null,
    'resolvedSeller' : IDL.Null,
  });
  const Dispute = IDL.Record({
    'status' : DisputeStatus,
    'resolutionNotes' : IDL.Text,
    'evidence' : IDL.Text,
    'transactionId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const VerificationLevel = IDL.Variant({
    'documentVerified' : IDL.Null,
    'basic' : IDL.Null,
    'fullyVerified' : IDL.Null,
  });
  const User = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'country' : IDL.Text,
    'balance' : IDL.Nat,
    'role' : UserRole,
    'trustScore' : IDL.Nat,
    'languages' : IDL.Vec(IDL.Text),
    'verification' : VerificationLevel,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'country' : IDL.Text,
    'balance' : IDL.Nat,
    'role' : UserRole,
    'trustScore' : IDL.Nat,
    'languages' : IDL.Vec(IDL.Text),
    'verification' : VerificationLevel,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const KYCStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const KYCSubmission = IDL.Record({
    'status' : KYCStatus,
    'documentBlob' : IDL.Opt(ExternalBlob),
    'documentType' : IDL.Text,
    'reviewerNotes' : IDL.Text,
    'user' : IDL.Principal,
    'description' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'kycUpdate' : IDL.Null,
    'transaction' : IDL.Null,
    'message' : IDL.Null,
    'dispute' : IDL.Null,
    'systemNotification' : IDL.Null,
  });
  const Notification = IDL.Record({
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'read' : IDL.Bool,
    'user' : IDL.Principal,
    'message' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'disputed' : IDL.Null,
    'initiated' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'escrowed' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createConversation' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'createDispute' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createListing' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'createReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAllOpenDisputes' : IDL.Func([], [IDL.Vec(Dispute)], ['query']),
    'getAllSuspendedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getPendingKYCSubmissions' : IDL.Func(
        [],
        [IDL.Vec(KYCSubmission)],
        ['query'],
      ),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementListingViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'recordTransaction' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitKYC' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'suspendListing' : IDL.Func([IDL.Text], [], []),
    'updateDisputeStatus' : IDL.Func(
        [IDL.Text, DisputeStatus, IDL.Text],
        [],
        [],
      ),
    'updateKYCStatus' : IDL.Func([IDL.Principal, KYCStatus, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, AdStatus],
        [],
        [],
      ),
    'updateTransactionStatus' : IDL.Func([IDL.Text, TransactionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };