/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Listing {
    id: string;
    status: AdStatus;
    title: string;
    views: bigint;
    seller: Principal;
    processingTime: string;
    currency: string;
    category: string;
    originCountry: string;
    price: bigint;
    destinationCountry: string;
    requirements: Array<string>;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface User {
    bio: string;
    principal: Principal;
    country: string;
    balance: bigint;
    role: UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: VerificationLevel;
}
export interface KYCSubmission {
    status: KYCStatus;
    documentBlob?: ExternalBlob;
    documentType: string;
    reviewerNotes: string;
    user: Principal;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Dispute {
    status: DisputeStatus;
    resolutionNotes: string;
    evidence: string;
    transactionId: string;
    reason: string;
}
export interface Notification {
    title: string;
    notifType: NotificationType;
    read: boolean;
    user: Principal;
    message: string;
}
export interface Message {
    text: string;
    sender: Principal;
    timestamp: Time;
}
export interface UserProfile {
    bio: string;
    country: string;
    balance: bigint;
    role: UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: VerificationLevel;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AdStatus {
    active = "active",
    expired = "expired",
    suspended = "suspended",
    draft = "draft"
}
export enum DisputeStatus {
    closed = "closed",
    underReview = "underReview",
    open = "open",
    resolvedBuyer = "resolvedBuyer",
    resolvedSeller = "resolvedSeller"
}
export enum KYCStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum NotificationType {
    kycUpdate = "kycUpdate",
    transaction = "transaction",
    message = "message",
    dispute = "dispute",
    systemNotification = "systemNotification"
}
export enum TransactionStatus {
    disputed = "disputed",
    initiated = "initiated",
    completed = "completed",
    refunded = "refunded",
    escrowed = "escrowed"
}
export enum UserRole {
    admin = "admin",
    moderator = "moderator",
    seller = "seller",
    buyer = "buyer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationLevel {
    documentVerified = "documentVerified",
    basic = "basic",
    fullyVerified = "fullyVerified"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMessage(conversationId: string, text: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createConversation(conversationId: string, sellerId: Principal, adId: string): Promise<void>;
    createDispute(transactionId: string, reason: string, evidence: string): Promise<void>;
    createListing(title: string, category: string, price: bigint): Promise<string>;
    createReview(transactionId: string, adId: string, rating: bigint, comment: string): Promise<void>;
    createUser(country: string, bio: string, role: UserRole): Promise<void>;
    getAllListings(): Promise<Array<Listing>>;
    getAllListingsBySeller(sellerId: Principal): Promise<Array<Listing>>;
    getAllOpenDisputes(): Promise<Array<Dispute>>;
    getAllSuspendedListings(): Promise<Array<Listing>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getListing(listingId: string): Promise<Listing>;
    getMessages(conversationId: string): Promise<Array<Message>>;
    getPendingKYCSubmissions(): Promise<Array<KYCSubmission>>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementListingViews(listingId: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(index: bigint): Promise<void>;
    recordTransaction(sellerId: Principal, adId: string, amount: bigint): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitKYC(documentType: string, description: string): Promise<void>;
    suspendListing(listingId: string): Promise<void>;
    updateDisputeStatus(transactionId: string, status: DisputeStatus, resolutionNotes: string): Promise<void>;
    updateKYCStatus(user: Principal, status: KYCStatus, reviewerNotes: string): Promise<void>;
    updateListing(listingId: string, title: string, category: string, price: bigint, status: AdStatus): Promise<void>;
    updateTransactionStatus(transactionId: string, status: TransactionStatus): Promise<void>;
}
import type { AdStatus as _AdStatus, Dispute as _Dispute, DisputeStatus as _DisputeStatus, ExternalBlob as _ExternalBlob, KYCStatus as _KYCStatus, KYCSubmission as _KYCSubmission, Listing as _Listing, Notification as _Notification, NotificationType as _NotificationType, TransactionStatus as _TransactionStatus, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, VerificationLevel as _VerificationLevel, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createConversation(arg0: string, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0, arg1, arg2);
            return result;
        }
    }
    async createDispute(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDispute(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDispute(arg0, arg1, arg2);
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2);
            return result;
        }
    }
    async createReview(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListingsBySeller(arg0: Principal): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListingsBySeller(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListingsBySeller(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOpenDisputes(): Promise<Array<Dispute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenDisputes();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenDisputes();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSuspendedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSuspendedListings();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSuspendedListings();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: string): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_Listing_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_Listing_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getPendingKYCSubmissions(): Promise<Array<KYCSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingKYCSubmissions();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingKYCSubmissions();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementListingViews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementListingViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementListingViews(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async recordTransaction(arg0: Principal, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitKYC(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKYC(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKYC(arg0, arg1);
            return result;
        }
    }
    async suspendListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendListing(arg0);
            return result;
        }
    }
    async updateDisputeStatus(arg0: string, arg1: DisputeStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisputeStatus(arg0, to_candid_DisputeStatus_n51(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisputeStatus(arg0, to_candid_DisputeStatus_n51(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateKYCStatus(arg0: Principal, arg1: KYCStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKYCStatus(arg0, to_candid_KYCStatus_n53(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKYCStatus(arg0, to_candid_KYCStatus_n53(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: AdStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, to_candid_AdStatus_n55(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, to_candid_AdStatus_n55(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateTransactionStatus(arg0: string, arg1: TransactionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransactionStatus(arg0, to_candid_TransactionStatus_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransactionStatus(arg0, to_candid_TransactionStatus_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdStatus): AdStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DisputeStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisputeStatus): DisputeStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Dispute_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dispute): Dispute {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_KYCStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KYCStatus): KYCStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_KYCSubmission_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KYCSubmission): Promise<KYCSubmission> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_User_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationLevel): VerificationLevel {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AdStatus;
    title: string;
    views: bigint;
    seller: Principal;
    processingTime: string;
    currency: string;
    category: string;
    originCountry: string;
    price: bigint;
    destinationCountry: string;
    requirements: Array<string>;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    status: AdStatus;
    title: string;
    views: bigint;
    seller: Principal;
    processingTime: string;
    currency: string;
    category: string;
    originCountry: string;
    price: bigint;
    destinationCountry: string;
    requirements: Array<string>;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_AdStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        views: value.views,
        seller: value.seller,
        processingTime: value.processingTime,
        currency: value.currency,
        category: value.category,
        originCountry: value.originCountry,
        price: value.price,
        destinationCountry: value.destinationCountry,
        requirements: value.requirements,
        images: await from_candid_vec_n17(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DisputeStatus;
    resolutionNotes: string;
    evidence: string;
    transactionId: string;
    reason: string;
}): {
    status: DisputeStatus;
    resolutionNotes: string;
    evidence: string;
    transactionId: string;
    reason: string;
} {
    return {
        status: from_candid_DisputeStatus_n22(_uploadFile, _downloadFile, value.status),
        resolutionNotes: value.resolutionNotes,
        evidence: value.evidence,
        transactionId: value.transactionId,
        reason: value.reason
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    country: string;
    balance: bigint;
    role: _UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: _VerificationLevel;
}): {
    bio: string;
    principal: Principal;
    country: string;
    balance: bigint;
    role: UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: VerificationLevel;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        country: value.country,
        balance: value.balance,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        trustScore: value.trustScore,
        languages: value.languages,
        verification: from_candid_VerificationLevel_n29(_uploadFile, _downloadFile, value.verification)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    country: string;
    balance: bigint;
    role: _UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: _VerificationLevel;
}): {
    bio: string;
    country: string;
    balance: bigint;
    role: UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: VerificationLevel;
} {
    return {
        bio: value.bio,
        country: value.country,
        balance: value.balance,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        trustScore: value.trustScore,
        languages: value.languages,
        verification: from_candid_VerificationLevel_n29(_uploadFile, _downloadFile, value.verification)
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _KYCStatus;
    documentBlob: [] | [_ExternalBlob];
    documentType: string;
    reviewerNotes: string;
    user: Principal;
    description: string;
}): Promise<{
    status: KYCStatus;
    documentBlob?: ExternalBlob;
    documentType: string;
    reviewerNotes: string;
    user: Principal;
    description: string;
}> {
    return {
        status: from_candid_KYCStatus_n39(_uploadFile, _downloadFile, value.status),
        documentBlob: record_opt_to_undefined(await from_candid_opt_n41(_uploadFile, _downloadFile, value.documentBlob)),
        documentType: value.documentType,
        reviewerNotes: value.reviewerNotes,
        user: value.user,
        description: value.description
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    notifType: _NotificationType;
    read: boolean;
    user: Principal;
    message: string;
}): {
    title: string;
    notifType: NotificationType;
    read: boolean;
    user: Principal;
    message: string;
} {
    return {
        title: value.title,
        notifType: from_candid_NotificationType_n45(_uploadFile, _downloadFile, value.notifType),
        read: value.read,
        user: value.user,
        message: value.message
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    suspended: null;
} | {
    draft: null;
}): AdStatus {
    return "active" in value ? AdStatus.active : "expired" in value ? AdStatus.expired : "suspended" in value ? AdStatus.suspended : "draft" in value ? AdStatus.draft : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    underReview: null;
} | {
    open: null;
} | {
    resolvedBuyer: null;
} | {
    resolvedSeller: null;
}): DisputeStatus {
    return "closed" in value ? DisputeStatus.closed : "underReview" in value ? DisputeStatus.underReview : "open" in value ? DisputeStatus.open : "resolvedBuyer" in value ? DisputeStatus.resolvedBuyer : "resolvedSeller" in value ? DisputeStatus.resolvedSeller : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    moderator: null;
} | {
    seller: null;
} | {
    buyer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "moderator" in value ? UserRole.moderator : "seller" in value ? UserRole.seller : "buyer" in value ? UserRole.buyer : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documentVerified: null;
} | {
    basic: null;
} | {
    fullyVerified: null;
}): VerificationLevel {
    return "documentVerified" in value ? VerificationLevel.documentVerified : "basic" in value ? VerificationLevel.basic : "fullyVerified" in value ? VerificationLevel.fullyVerified : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): KYCStatus {
    return "pending" in value ? KYCStatus.pending : "approved" in value ? KYCStatus.approved : "rejected" in value ? KYCStatus.rejected : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kycUpdate: null;
} | {
    transaction: null;
} | {
    message: null;
} | {
    dispute: null;
} | {
    systemNotification: null;
}): NotificationType {
    return "kycUpdate" in value ? NotificationType.kycUpdate : "transaction" in value ? NotificationType.transaction : "message" in value ? NotificationType.message : "dispute" in value ? NotificationType.dispute : "systemNotification" in value ? NotificationType.systemNotification : value;
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dispute>): Array<Dispute> {
    return value.map((x)=>from_candid_Dispute_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n25(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KYCSubmission>): Promise<Array<KYCSubmission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_KYCSubmission_n37(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n43(_uploadFile, _downloadFile, x));
}
function to_candid_AdStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdStatus): _AdStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_DisputeStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisputeStatus): _DisputeStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_KYCStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYCStatus): _KYCStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): _TransactionStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationLevel_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationLevel): _VerificationLevel {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    country: string;
    balance: bigint;
    role: UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: VerificationLevel;
}): {
    bio: string;
    country: string;
    balance: bigint;
    role: _UserRole;
    trustScore: bigint;
    languages: Array<string>;
    verification: _VerificationLevel;
} {
    return {
        bio: value.bio,
        country: value.country,
        balance: value.balance,
        role: to_candid_UserRole_n10(_uploadFile, _downloadFile, value.role),
        trustScore: value.trustScore,
        languages: value.languages,
        verification: to_candid_VerificationLevel_n49(_uploadFile, _downloadFile, value.verification)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    moderator: null;
} | {
    seller: null;
} | {
    buyer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.moderator ? {
        moderator: null
    } : value == UserRole.seller ? {
        seller: null
    } : value == UserRole.buyer ? {
        buyer: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationLevel): {
    documentVerified: null;
} | {
    basic: null;
} | {
    fullyVerified: null;
} {
    return value == VerificationLevel.documentVerified ? {
        documentVerified: null
    } : value == VerificationLevel.basic ? {
        basic: null
    } : value == VerificationLevel.fullyVerified ? {
        fullyVerified: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisputeStatus): {
    closed: null;
} | {
    underReview: null;
} | {
    open: null;
} | {
    resolvedBuyer: null;
} | {
    resolvedSeller: null;
} {
    return value == DisputeStatus.closed ? {
        closed: null
    } : value == DisputeStatus.underReview ? {
        underReview: null
    } : value == DisputeStatus.open ? {
        open: null
    } : value == DisputeStatus.resolvedBuyer ? {
        resolvedBuyer: null
    } : value == DisputeStatus.resolvedSeller ? {
        resolvedSeller: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYCStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == KYCStatus.pending ? {
        pending: null
    } : value == KYCStatus.approved ? {
        approved: null
    } : value == KYCStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdStatus): {
    active: null;
} | {
    expired: null;
} | {
    suspended: null;
} | {
    draft: null;
} {
    return value == AdStatus.active ? {
        active: null
    } : value == AdStatus.expired ? {
        expired: null
    } : value == AdStatus.suspended ? {
        suspended: null
    } : value == AdStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): {
    disputed: null;
} | {
    initiated: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    escrowed: null;
} {
    return value == TransactionStatus.disputed ? {
        disputed: null
    } : value == TransactionStatus.initiated ? {
        initiated: null
    } : value == TransactionStatus.completed ? {
        completed: null
    } : value == TransactionStatus.refunded ? {
        refunded: null
    } : value == TransactionStatus.escrowed ? {
        escrowed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
